# Generated by Django 5.0.2 on 2024-04-07 10:47

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 7, 16, 17, 57, 293827))),
                ('doctor', models.IntegerField(default=0, null=True)),
                ('timeslot', models.TimeField(null=True)),
                ('type', models.CharField(choices=[(1, 'surgery'), (2, 'emergency'), (3, 'follow up')], max_length=20)),
                ('surgtype', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAdmits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appid', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('docid', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(1, 'admitted'), (2, 'discharged')], max_length=20)),
                ('report', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(1, 'AD'), (2, 'DR')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('speciality', models.CharField(max_length=20)),
                ('surgeries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None)),
                ('age', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('weight', models.IntegerField(default=0)),
                ('dob', models.DateField(default='2024-04-07')),
                ('bloodgrp', models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-')], max_length=20)),
                ('maritalstat', models.CharField(choices=[(1, 'married'), (2, 'single'), (3, 'divorced')], max_length=20)),
                ('occupation', models.CharField(max_length=500)),
                ('medhist', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepScans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('docid', models.IntegerField(default=0)),
                ('report', models.ImageField(default='hello.jpg', upload_to='media')),
                ('comments', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(1, 'OT'), (2, 'consultation'), (3, 'ward')], max_length=20)),
                ('floor', models.IntegerField(default=0)),
                ('equipped', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('reasonfvisit', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None)),
                ('symptoms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None)),
                ('vitals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None)),
            ],
        ),
    ]
