# Generated by Django 5.0.2 on 2024-04-07 10:49

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0005_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 16, 19, 39, 386425)),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 16, 19, 39, 386425)),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='medhist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
        ),
    ]
