# Generated by Django 5.0.2 on 2024-04-07 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0007_alter_appointments_date_alter_patientdata_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='dob',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 16, 24, 37, 711896)),
        ),
    ]
