# Generated by Django 5.0.2 on 2024-04-07 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0010_alter_appointments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='medhist',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 16, 31, 44, 634774)),
        ),
    ]
