# Generated by Django 5.0.2 on 2024-04-07 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0011_remove_patientdata_medhist_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 16, 39, 9, 13656)),
        ),
    ]
