# Generated by Django 5.0.2 on 2024-04-07 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0012_alter_appointments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='type',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 17, 54, 15, 1417)),
        ),
    ]
