# Generated by Django 5.0.2 on 2024-04-07 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0013_remove_appointments_type_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 19, 48, 55, 473051)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.CharField(default='', null=True),
        ),
    ]
