# Generated by Django 5.0.2 on 2024-04-07 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0014_alter_appointments_date_alter_appointments_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitLog',
        ),
        migrations.AddField(
            model_name='currentadmits',
            name='currentdiagnosis',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='currentadmits',
            name='currentdosage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentadmits',
            name='currentmedication',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 22, 29, 20, 854567)),
        ),
    ]
