# Generated by Django 5.0.2 on 2024-04-08 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0016_dbsearches_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 8, 8, 13, 25, 237369)),
        ),
    ]
